export const MQTT_CONNECTION_STATUS = {
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  CONNECTING: 'CONNECTING',
  ERROR: 'ERROR',
  RECONNECTING: 'RECONNECTING',
  UNKNOWN: 'UNKNOWN',
} as const;

export type MQTTConnectionStatusType =
  (typeof MQTT_CONNECTION_STATUS)[keyof typeof MQTT_CONNECTION_STATUS];
