[io]
[io.adc]
enabled = false

[io.can]
enabled = false

[io.gpio]
enabled = false

[io.i2c]
enabled = false

[io.pwm]
enabled = false

[io.spi]
enabled = false

[io.uart]
enabled = false

[sensors]
[sensors.accelerometer]
enabled = false
bus = 2
address = 25

[sensors.temperature]
enabled = false
bus = 1
address = 0x38

[sensors.bms]
enabled = false
bus = "can1"

[sensors.tof]
enabled = true
bus = 2
address = 29

[motors]
enabled = false
bus = "can1"

[aliases]
"example" = "help"
