[io]
[io.adc]
enabled = false
pins = []

[io.can]
enabled = false
buses = ["can1"]

[io.gpio]
enabled = false
read_pins = []
write_pins = []

[io.i2c]
enabled = false
buses = []

[io.pwm]
enabled = false
modules = []
period = []

[io.spi]
enabled = false
buses = []

[io.uart]
enabled = false
buses = []

[sensors]
[sensors.accelerometer]
enabled = false
bus = 2
address = 25

[sensors.temperature]
enabled = false
bus = 2
address = 56

[sensors.bms]
enabled = false
bus = "can1"

[sensors.inverter_current]
enabled = false
bus = 2
adc_mux_channel = 0

[motors]
enabled = false
bus = "can1"

[aliases]
"example" = "help"
