[io]
[io.adc]
enabled = false

[io.can]
enabled = false

[io.gpio]
enabled = false

[io.i2c]
enabled = false

[io.pwm]
enabled = false

[io.spi]
enabled = false

[io.uart]
enabled = false

[sensors]
[sensors.accelerometer]
enabled = false
bus = 2
address = 29
mux_channel = 0

[sensors.temperature]
enabled = false
bus = 1
address = 0x38

[sensors.bms]
enabled = false
bus = "can1"

[sensors.inverter_current]
enabled = false
bus = 2
adc_mux_channel = 0

[sensors.keyence]
enabled = false
pin = 1

[motors]
enabled = false
bus = "can1"

[aliases]
"example" = "help"
