[io]
[io.adc]
enabled = false

[io.can]
enabled = false

[io.gpio]
enabled = false

[io.i2c]
enabled = false

[io.pwm]
enabled = false

[io.spi]
enabled = false

[io.uart]
enabled = false

[sensors]
[sensors.accelerometer]
enabled = false
bus = 2
address = 25

[sensors.temperature]
enabled = false
bus = 2
address = 56

[sensors.optical_flow]
enabled = false
bus = 0
mode = 0
word_size = 8
bit_order = 0
clock = 2'000'000

[sensors.bms]
enabled = false
bus = "can1"

[motors]
enabled = false
bus = "can1"

[aliases]
"example" = "help"
