[hostnames]
raspberry = "192.168.1.0"
banoffee = "192.168.1.1"
pumpkin = "192.168.1.2"
rhubarb = "192.168.1.3"

[mqtt]
host = "192.168.1.0"
port = 4556

[raspberry]
nodes = ["state_machine", "mqtt_broker"]

[state_machine]
# Possible transition tables are "full_run",
# "no_levitation", "levitation_only"
transition_table = "full_run"

[some_sensors]
[some_sensors.accelerometer]
count = 5
upper_limit = 100
lower_limit = 0
name = 'Acceleration'
topic = 'accelerometer'
format = 'float'
type = 'acceleration'
unit = 'm/s²'
