name: Build

on: push

jobs:
  build:
    name: Build and lint
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      # Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run build
        run: ./docker.sh -r -c -b -l
