name: Build

on:
  push:
    paths-ignore:
      - 'telemetry/**'

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      # Setup Docker Builx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run build
        run: ./build.sh -r -c
