name: Telemetry Build

on:
  push:
    paths:
      - 'telemetry/**'

jobs:
  telemetry-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: telemetry
    steps:
      - uses: actions/checkout@v3

      - name: Docker
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: ./build.sh
