name: Telemetry Build

on:
  push:
    paths:
      - 'telemetry/**'
      - '.github/workflows/telemetry.yml'

jobs:
  telemetry-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: telemetry
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.12

      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
