name: Build Telemetry

on:
  push:
    paths:
      - 'telemetry/**'

jobs:
  telemetry-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: telemetry

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
