name: Telemetry

on: push

defaults:
  run:
    working-directory: telemetry

jobs:
  telemetry:
    name: Telemetry Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker
        uses: docker/setup-buildx-action@v3

      - name: Lint
        run: ./telemetry.sh ci

  telemetry-formatting:
    name: Telemetry Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm and Prettier
        run: |
          npm install -g pnpm
          npm install -g prettier@3.2.4

      - name: Check Formatting
        run: pnpm run format:check
