name: Telemetry Build

on:
  push:
    paths:
      - 'telemetry/**'
      - '.github/workflows/telemetry.yml'

jobs:
  telemetry-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: telemetry
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.14.0'
          cache: 'pnpm'
          cache-dependency-path: 'telemetry/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
