name: Telemetry Linter

on:
  push:
    paths:
      - 'telemetry/**'

jobs:
  run-linters:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: telemetry

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: 'telemetry/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
