name: Telemetry

on: push

defaults:
  run:
    working-directory: telemetry

jobs:
  telemetry-build:
    name: Telemetry Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: ./build.sh

  telemetry-lint:
    name: Telemetry Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --filter eslint-config

      - name: Lint
        run: pnpm run lint

  telemetry-formatting:
    name: Telemetry Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm and Prettier
        run: |
          npm install -g pnpm
          npm install -g prettier@3.2.4

      - name: Check Formatting
        run: pnpm run format:check
