name: Telemetry Build

on:
  push:
    paths:
      - "telemetry/**"

jobs:
  telemetry-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: telemetry
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.14.0"
          cache: "yarn"
          cache-dependency-path: "telemetry/yarn.lock"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
