name: Telemetry

on: push

defaults:
  run:
    working-directory: telemetry

jobs:
  telemetry-build:
    name: Telemetry Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: ./build.sh

  telemetry-lint:
    name: Telemetry Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker
        uses: docker/setup-buildx-action@v3

      - name: Lint
        run: ./telemetry.sh lint
